### ISSUE TITLE
Consider replacing fcntl with portalocker for Windows support

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/lib-cove#53]
It's not available on Windows.

**Comment by Bjwebb** [comment]
It's used for file locking in https://github.com/OpenDataServices/lib-cove/blob/0bc725bb6707789f3930daaf590d383a368b5d1f/libcove/lib/common.py#L1241-L1270

We could take a different approach to this, but I'm not quite sure how much work it would be.

**Comment by jpmckinney** [comment]
Why do we need to lock the file, though? In what scenario would there be simultaneous writes?

**Comment by Bjwebb** [comment]
This gets called from cove-ocds web requests, where we may have multiple processes/threads calling this function at once.

**Comment by jpmckinney** [comment]
Aha. Renamed issue and found this library that can perhaps be used to support multiple operating systems: https://pypi.org/project/portalocker/

**Comment by benvand** [comment]
My proposal for safely removing the file locking

The 2 race conditions to account for are:

Process A checks for the existence of the file finds none
Process B checks for the existence of the file finds none
Process A/ B writes new file
Process A/ B writes new file

Process A checks for the existence of the file finds none
Process A opens file for writing
Process B checks for the existence of the file
Process B opens the file
Process B reads nothing
Process A writes to file

In the first case we don't care because the data is never mutated and gathered from the same source.
In the second case the trick is to write the file before you ever open it :) Create a temp file, write to that, then rename it.

This wouldn't work in cases where data is mutated, but it does in ours.

Also added tests

**Comment by jpmckinney** [comment]
Closed by #74

**Comment by jpmckinney** [comment]
@Bjwebb You can close this issue to declutter issue tracker.
